'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    await queryInterface.bulkInsert('actors', [{
       id: 1,
       created_at: new Date,
       updated_at: new Date,
       first_name: "Antonio",
       last_name: "Gasalla",
       rating: 8.6,
       favorite_movie_id: 1,
     },
     {
      id: 2,
      created_at: new Date,
      updated_at: new Date,
      first_name: "China",
      last_name: "Zorrilla",
      rating: 8,
      favorite_movie_id: 1,
    },
    {
      id: 3,
      created_at: new Date,
      updated_at: new Date,
      first_name: "Luis",
      last_name: "Brandoni",
      rating: 8.3,
      favorite_movie_id: 9,
    }, 
    {
      id: 4,
      created_at: new Date,
      updated_at: new Date,
      first_name: "Luis",
      last_name: "Luque",
      rating: 7.2,
      favorite_movie_id: 2,
    },
    {
      id: 5,
      created_at: new Date,
      updated_at: new Date,
      first_name: "Diego",
      last_name: "Peretti",
      rating: 9.2,
      favorite_movie_id: 2,
    },
    {
      id: 6,
      created_at: new Date,
      updated_at: new Date,
      first_name: "Julieta",
      last_name: "Díaz",
      rating: 8.1,
      favorite_movie_id: 2,
    },
    {
      id: 7,
      created_at: new Date,
      updated_at: new Date,
      first_name: "Ricardo",
      last_name: "Darín",
      rating: 9.3,
      favorite_movie_id: 4,
    },
    {
      id: 8,
      created_at: new Date,
      updated_at: new Date,
      first_name: "Gastón",
      last_name: "Pauls",
      rating: 7.7,
      favorite_movie_id: 3,
    },
    {
      id: 9,
      created_at: new Date,
      updated_at: new Date,
      first_name: "Soledad",
      last_name: "Villamil",
      rating: 7.5,
      favorite_movie_id: 4,
    },
    {
      id: 10,
      created_at: new Date,
      updated_at: new Date,
      first_name: "Pablo",
      last_name: "Rago",
      rating: 7.9,
      favorite_movie_id: 4,
    },
    {
      id: 11,
      created_at: new Date,
      updated_at: new Date,
      first_name: "Érica",
      last_name: "Rivas",
      rating: 8.2,
      favorite_movie_id: 5,
    },
    {
      id: 12,
      created_at: new Date,
      updated_at: new Date,
      first_name: "Leonardo",
      last_name: "Sbaraglia",
      rating: 7.9,
      favorite_movie_id: 5,
    },
    {
      id: 13,
      created_at: new Date,
      updated_at: new Date,
      first_name: "Norma",
      last_name: "Aleandro",
      rating: 7,
      favorite_movie_id: 6,
    },
    {
      id: 14,
      created_at: new Date,
      updated_at: new Date,
      first_name: "Héctor",
      last_name: "Alterio",
      rating: 8,
      favorite_movie_id: 6,
    },
    {
      id: 15,
      created_at: new Date,
      updated_at: new Date,
      first_name: "Germán",
      last_name: "Kraus",
      rating: 6.6,
      favorite_movie_id: 7,
    },
    {
      id: 16,
      created_at: new Date,
      updated_at: new Date,
      first_name: "Lorenzo",
      last_name: "Ferro",
      rating: 7.2,
      favorite_movie_id: 8,
    },
    {
      id: 17,
      created_at: new Date,
      updated_at: new Date,
      first_name: "Peter",
      last_name: "Lanzani",
      rating: 8.4,
      favorite_movie_id: 8,
    },
    {
      id: 18,
      created_at: new Date,
      updated_at: new Date,
      first_name: "Dady",
      last_name: "Brieva",
      rating: 6.9,
      favorite_movie_id: 9,
    },
    {
      id: 19,
      created_at: new Date,
      updated_at: new Date,
      first_name: "Alberto",
      last_name: "Olmedo",
      rating: 7.3,
      favorite_movie_id: 10,
    },
    {
      id: 20,
      created_at: new Date,
      updated_at: new Date,
      first_name: "Jorge",
      last_name: "Porcel",
      rating: 7.5,
      favorite_movie_id: 10,
    },
    ], {});
    
  },

  async down (queryInterface, Sequelize) {
    await queryInterface.bulkDelete('actors', null, {});
     
  }
};
