"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "movies",
      [
        {
          id: 1,
          created_at: new Date(),
          updated_at: new Date(),
          title: "Esperando la Carroza",
          rating: 7.4,
          awards: 2,
          release_date: "1985-05-06",
          length: 94,
          genre_id: 1,
        },
        {
          id: 2,
          created_at: new Date(),
          updated_at: new Date(),
          title: "Tiempo de Valientes",
          rating: 8.6,
          awards: 3,
          release_date: "2005-08-19",
          length: 107,
          genre_id: 13,
        },
        {
          id: 3,
          created_at: new Date(),
          updated_at: new Date(),
          title: "Nueve Reinas",
          rating: 8,
          awards: 1,
          release_date: "2000-05-31",
          length: 114,
          genre_id: 4,
        },
        {
          id: 4,
          created_at: new Date(),
          updated_at: new Date(),
          title: "El secreto de sus ojos",
          rating: 9.1,
          awards: 5,
          release_date: "2009-08-13",
          length: 129,
          genre_id: 3,
        },
        {
          id: 5,
          created_at: new Date(),
          updated_at: new Date(),
          title: "Relatos salvajes",
          rating: 8.7,
          awards: 3,
          release_date: "2014-08-21",
          length: 122,
          genre_id: 1,
        },
        {
          id: 6,
          created_at: new Date(),
          updated_at: new Date(),
          title: "La historia oficial",
          rating: 8.4,
          awards: 2,
          release_date: "1985-04-03",
          length: 112,
          genre_id: 9,
        },
        {
          id: 7,
          created_at: new Date(),
          updated_at: new Date(),
          title: "Dibu: la película",
          rating: 7,
          awards: 0,
          release_date: "1997-07-10",
          length: 78,
          genre_id: 10,
        },
        {
          id: 8,
          created_at: new Date(),
          updated_at: new Date(),
          title: "El Ángel",
          rating: 8.3,
          awards: 2,
          release_date: "2018-08-09",
          length: 118,
          genre_id: 13,
        },
        {
        id: 9,
        created_at: new Date(),
        updated_at: new Date(),
        title: "El ciudadano ilustre",
        rating: 7.9,
        awards: 2,
        release_date: "2016-09-08",
        length: 118,
        genre_id: 1,
      },
      {
        id: 10,
        created_at: new Date(),
        updated_at: new Date(),
        title: "Rambito y Rambón, primera misión",
        rating: 6.5,
        awards: 0,
        release_date: "1986-08-07",
        length: 90,
        genre_id: 1,
      },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("movies", null, {});
  },
};
